baseURL = "https://katmatt.github.io/"
languageCode = "en-us"
title = "katmatt blogs"
theme = "hugo-kiera"
pygmentsCodeFences = true

[author]
    name = "Matthias Köster"
    github = "katmatt"
    linkedin = "matthias-köster-12159636"
    twitter = "matthiaskoester"

[params]
    UtterancesRepo = "katmatt/katmatt-blogs"
    UtterancesIssueTerm = "pathname"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
