name: Build and publish blog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.68.3
          extended: true
      - name: Run hugo - build blog
        run: hugo --minify
        env:
          HUGO_GOOGLEANALYTICS: UA-173228040-1
      - name: Deploy blog to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
